dist: trusty
language: node_js
node_js: '8'
sudo: required
services:
- docker
addons:
  firefox: latest
  apt:
    sources:
     - google-chrome
    packages:
     - google-chrome-stable fluxbox
  sonarcloud:
    organization: ""
    token:
      secure: "q4BRqVcOgiFXRAHVZwZCaeGvqdmPiPrM1MYxvoo7d5XBVNFpZ0faNwP6RQRWAtDVp7uT5Z5EvwmPdv2sHQXPQLfHBuGusO8keBwbnNPA/1abHS/bWUIImU7uFoGoavB04hySxxh8i+ZPS7f4Jc+Wsnss2zHc0k2Uo0hPhoQA0OaUoABZmNocCkmyMH7kZEaM4jmIW0uDVM3O58ScY/GUUWlX3ONrR0H/ioC2mTH7sDJ2U4THwYwK3mSQPAK4mQgOYaOkiG+s9DhF8wevXQl5Pdm1pHJce6IxJioIWhN/5+SZTIkgospYOqJB/6f/Fhw83yLXe/J/yQBi+PETX7knRRDixQce0OUDnOtV1pQknHnYFOKL9/m90KgjBG4ERD0gHzUpUIPDXZhbixTwWjOva0KvD4C3JJuYl56FH1+n30trp1jhacP01UNiCkCrQgWNbFFasanRE8MZWijrAWy1lHp5u5JjZxd3mtUrxeQLLLXFTXkwZ7WWywSBVpAo78pZZ3R/ceJgkd8h3A966EN5a/RRdnjiRluu67Z2QhV235yZ5Xa7jtAznkvYNRs46JVYYf5Sl5IdmSmlZ0o652yjaQSEicdv/KwJg0PLiNI5S5KA6z9fPQa1R1W4uxYnv+kJvbB0IYApaPUVPAujJORu5jgfeEJF277q/8ZJCA5G3Qc="

before_install:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- . ./scripts/prepare-repo
- stty cols 80
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 3
- fluxbox >/dev/null 2>&1 &
- . ./scripts/k8s/init

install:
- yarn
- yarn tslint
- sonar-scanner
- yarn ci-test
- yarn build

script:
- yarn docker
- yarn docker:push
- yarn docker:deploy
- yarn git:push
notifications:
  slack:
    secure: PLOOGvncNtcFT2cnaxPXKoyTFXwbZiFqhj9HL2BszN2rwi9i3cEFsSuS8Q/8Twj2VDcAx/qnTIhO40izsJj679N7JX7/Y60irFzZrG5KOzFdgGRQooV5v8ZnltRFb+o4M9wqOCpGCKSgmpUb2IwrFpjcqcJcTDsz/66XXSVDnJgGbXJ9rj66Fp/q7WGeszVadp7rNcjv/uau0z1CS5nqXN51MJ21Gt4VQTz3U5Ys9Yn6fNScj4DLbDXXLUsmIsqzX4s10lfwozV7VSqRlmtuXKW5Uq1zny8vIvPZlKNKmxR/mYoBj+WGFy32V72FI/XnXHSNDkuoEOjml8abgwFj22lPublCQdNALl2/Aw35KMOquMpi8CYs5AAytBTJ+zMAIS904jQjYwafi24kPaWJ24e32rSMPZYtv/LVGsbpXRkQOj2jT08Sj7J+a82u3r8MnDeeO0LHmolVK2Mnov3u/uY6s7V+M9GdEu9zjUqs/ZGvNtsN4e2bXrN8VKU6YXbrYejxtlx5OjdgbzTnfHCKHSvSBjBlOg7zNSszwBUE81HnmLOUI2WKU/77vddoxGZBj0OsvGgZbs9QwAFPSWFAT9UQuAEivUd9+KwbO0F7bkPN7VmGiWX6mY8upRFzqQu4j5WYbizyVqAs4iHGCCni4CPkbskFIS9erf100mFEMh4=
