version: '3'
services:
  server: 
    image: msw-server:latest
    restart: always
    ports:
      - 3000:3000
  cient:
    build: .
    image: msw-portal:e2e
    ports: 
      - "4200:4200"
    links:
      - server
    environment:
      - NODE_ENV=e2e-tests